### ISSUE TITLE
Cannot measure distance between world and world_nether

### ISSUE THREAD

**Issue by Xiang0418** [Georg-code/AFK-Kick#1]
I use this plugin on my papermc server but there were many of the following WARN

[20:50:14 WARN]: [AFK-Kick] Task #479 for AFK-Kick v1.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.4.jar:git-Paper-298]
        at ch.derhohi.main.Session.increaseMinute(Session.java:37) ~[?:?]
        at ch.derhohi.main.Main$1.run(Main.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-298]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-298]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[20:51:14 WARN]: [AFK-Kick] Task #479 for AFK-Kick v1.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.4.jar:git-Paper-298]
        at ch.derhohi.main.Session.increaseMinute(Session.java:37) ~[?:?]
        at ch.derhohi.main.Main$1.run(Main.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-298]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-298]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[20:53:14 WARN]: [AFK-Kick] Task #479 for AFK-Kick v1.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.4.jar:git-Paper-298]
        at ch.derhohi.main.Session.increaseMinute(Session.java:37) ~[?:?]
        at ch.derhohi.main.Main$1.run(Main.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-298]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-298]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-298]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by Georg-code** [comment]
Hey, sorry for the delay! I will fix this in the following days. 
Thanks for the bug report!
Have a nice day!

**Comment by Flockcode** [comment]
Thanks!
I will fix this in the near future!

**Comment by Markus-blip** [comment]
Made a pull request, should fix this!

**Comment by Flockcode** [comment]
Thanks Markus
